version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  win: circleci/windows@2.4.1

jobs:
  test:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
         working_directory: ~/project/test/Appel.SharpTemplate.Tests
         name: Run tests
         command: |
           dotnet.exe test        
  deploy:
    docker:
      - image: cimg/base:2022.02 
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - checkout
      - run:
          name: Run docker build
          command: |            
            docker build -f src/Appel.SharpTemplate.API/Dockerfile .
      - heroku/install
      - run:
          name: Run heroku deploy
          command: |
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
      - heroku/push-docker-image:
          app-name: sharp-template-api
          process-types: web
      - heroku/release-docker-image:
          app-name: sharp-template-api
          process-types: web

workflows:
  heroku-deploy:
    jobs:
      - test
      - deploy:
          context:
            - sharp-template-context
