version: 2.1

jobs:
  build-test-deploy:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - setup_remote_docker:
          version: 20.10.11
      # Checkout the code as the first step.
      - checkout      
      # Then simply use the dotnet container as you'd expect and run your tests
      #- run:
      #    # Update this line with the directory that contains your tests project file
      #    working_directory: ~/project/test/Appel.SharpTemplate.Tests
      #    name: Run tests
      #    command: |
      #      dotnet test

      # Build the docker image
      - run:
          name: Run docker build
          command: |
            apt-get install curl
            curl -fsSL https://get.docker.com/ | sh
            docker build . 

      # Deploy to Heroku
      - heroku/install
      - run:
          name: Run heroku deploy
          command: |
            heroku container:login
      - heroku/push-docker-image:
          process-types: web
      - heroku/release-docker-image:
          process-types: web

orbs:
  # For using Heroku CLI commands.
  heroku: circleci/heroku@1.2.6

workflows:
  heroku-deploy:
    jobs:
      - build-test-deploy:
          context:
            - sharp-template-context
