version: 2.1

jobs:
  build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      # Checkout the code as the first step.
      - checkout
      # Then simply use the dotnet container as you'd expect and run your tests
      #- run:
      #    # Update this line with the directory that contains your tests project file
      #    working_directory: ~/project/test/Appel.SharpTemplate.Tests
      #    name: Run tests
      #    command: |
      #      dotnet test
      - run:
          name: Run build and push docker image
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login

workflows:
  sharpflow:
    jobs:
      - build-and-test:
          context:
            - sharp-template-context
