version: 2.1

jobs:
  # test:
  #   docker:
  #     - image: mcr.microsoft.com/dotnet/sdk:6.0
  #       auth:
  #         username: $DOCKERHUB_USER
  #         password: $DOCKERHUB_ACCESS_TOKEN
  #   steps:
  #     - checkout
  #     - run:
  #        working_directory: ~/project/test/Appel.SharpTemplate.Tests
  #        name: Run tests
  #        command: |
  #          dotnet test        
  deploy:
    docker:
      - image: cimg/base:2022.02 
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - checkout
      # - run:
      #     name: Run docker build
      #     command: |            
      #       docker build -f src/Appel.SharpTemplate.API/Dockerfile -t sharp-template-api .
      #       docker tag sharp-template-api guilhermeappel/sharp-template-api:latest
      #       docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PSWD
      #       docker push guilhermeappel/sharp-template-api:latest
      - run:
          name: Run heroku deploy
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push --app sharp-template-api web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release --app sharp-template-api web    

workflows:
  heroku-deploy:
    jobs:
      # - test
      - deploy:
          # requires:
          #   - test
          context:
            - sharp-template-context
