version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  windows: circleci/windows@2.4.1

jobs:
  build-test-deploy:
    docker:
      - image: cimg/base:2022.02
    steps:
      # - setup_remote_docker:
      #     version: 20.10.11
      - checkout      
      - run:
         working_directory: ~/project/test/Appel.SharpTemplate.Tests
         name: Run tests
         command: |
           dotnet.exe test

      - run:
          name: Run docker build
          command: |            
            docker build -f src/Appel.SharpTemplate.API/Dockerfile .

      - heroku/install
      - run:
          name: Run heroku deploy
          command: |
            heroku container:login
      - heroku/push-docker-image:
          process-types: web
      - heroku/release-docker-image:
          process-types: web

workflows:
  heroku-deploy:
    jobs:
      - build-test-deploy:
          context:
            - sharp-template-context
